# Generated by Django 5.1.6 on 2025-02-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='survey_qr_codes/'),
        ),
    ]
