# Generated by Django 5.1.6 on 2025-02-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
