# Generated by Django 5.1.6 on 2025-02-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_survey_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
